kind: pipeline
type: docker
name: default
steps:

  - name: build
    image: docker:dind
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
      - name: data
        path: /data
    commands:
    - "apk add --no-cache git"
    - "git clone https://rujak.id/saiful/vagrant.git"
    - "cd vagrant"
    - "docker build -t vagrant ."

  - name: test
    image: docker:latest
    commands:
    - echo this should pass

  - name: publish
    image: docker:latest
    commands:
    - echo this should pass

  - name: deliver
    image: docker:latest
    commands:
    - echo stage status is $DRONE_STAGE_STATUS
    - echo build status is $DRONE_BUILD_STATUS
    when:
      status:
      - success
      - failure
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: data
    host:
      path: /var/lib/docker