kind: pipeline
type: docker
name: default
steps:
  - name: build
    image: centos:centos7.9.2009
    commands:
    - "docker build -t centos7/centos:1.3 ."
  - name: test
    image: docker:latest
    commands:
    - echo this should pass
  - name: publish
    image: docker:latest
    commands:
    - echo this should pass
  - name: deliver
    image: docker:latest
    commands:
    - echo stage status is $DRONE_STAGE_STATUS
    - echo build status is $DRONE_BUILD_STATUS
    when:
      status:
      - success
      - failure
